# Generated by Django 6.0.2 on 2026-02-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
