# Generated by Django 6.0.2 on 2026-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_claim_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_recommendation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
