# Generated by Django 6.0.2 on 2026-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_claim_ai_flags_claim_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('health', 'Health'), ('car', 'Car'), ('property', 'Property'), ('any', 'Any')], max_length=20),
        ),
    ]
