# Generated by Django 6.0.2 on 2026-02-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_policy_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='vision_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
